### ISSUE TITLE
creating index using migration?

### ISSUE THREAD

**Issue by aprilmintacpineda** [fauna/faunadb-migrate#2]
Hi, does this module allow creating indexes on the `up` method?

**Comment by BrunoQuaresma** [comment]
Yeap, should be. Are you having troubles?

**Comment by aprilmintacpineda** [comment]
Yes, the documentation did not mention it...

**Comment by BrunoQuaresma** [comment]
Ahh ok, you can run any query inside of up() and down(). We will try to make it more explicit in the docs. Thanks for feedback.
